export const quotes = [

    "Muscle weighs more than fat.",
    "Strength training boosts metabolism.",
    "Hydration improves workout performance.",
    "Protein helps repair muscles.",
    "Sleep aids muscle recovery.",
    "Cardio burns calories fast.",
    "Stretching improves flexibility.",
    "Core strength prevents injuries.",
    "Weight loss needs a calorie deficit.",
    "Muscle growth needs progressive overload.",
    "Warm-ups reduce injury risk.",
    "Rest days are vital for gains.",
    "Muscle soreness is not always injury.",
    "High reps build endurance.",
    "Low reps build strength.",
    "Lifting heavy builds denser bones.",
    "Consistency beats intensity.",
    "Protein timing matters less than total intake.",
    "Balance training improves stability.",
    "Overtraining hurts progress.",
    "Muscles grow during rest, not workouts.",
    "Hydration helps joint health.",
    "Exercise boosts mood via endorphins.",
    "Compound exercises save time.",
    "Walking daily aids heart health.",

    "Warm up 5 minutes before lifting.",
    "Keep your core tight during lifts.",
    "Breathe out when exerting force.",
    "Drink water before and after workouts.",
    "Use proper form over heavy weights.",
    "Track your progress weekly.",
    "Stretch after workouts, not before.",
    "Get 7-9 hours of sleep nightly.",
    "Eat protein with every meal.",
    "Rest muscles 48 hours between sessions.",
    "Focus on slow, controlled movements.",
    "Use full range of motion always.",
    "Mix cardio with strength training.",
    "Avoid comparing yourself to others.",
    "Fuel workouts with carbs beforehand.",
    "Don’t skip leg day.",
    "Plan rest days to prevent burnout.",
    "Use weights that challenge you safely.",
    "Log workouts to stay motivated.",
    "Set realistic fitness goals.",
    "Wear proper shoes for support.",
    "Don’t hold your breath while lifting.",
    "Warm muscles stretch better.",
    "Listen to your body’s signals.",
    "Cool down with light cardio.",

    "I lift... donuts to my mouth.",
    "My favorite machine is the vending one.",
    "I workout because punching people is frowned upon.",
    "Running late counts as cardio, right?",
    "I do squats so my ass matches my sass.",
    "Gym rule #1: Don’t die.",
    "Gym? I thought you said gin.",
    "I lift cookies to my mouth daily.",
    "Exercise? I thought you said extra fries.",
    "I’m into fitness... fitness pizza in my mouth.",
    "I run... out of patience quickly.",
    "Burpees? More like slurpees!",
    "I gym to escape my responsibilities.",
    "My warm-up is walking to the fridge.",
    "I’m training for a Netflix marathon.",
    "I gym so I can eat like a raccoon at midnight.",
    "I'm working on my before picture.",
    "My favorite exercise is a cross between a lunge and a crunch – lunch.",
    "Treadmills: nature's lie detector.",
    "Sweating is my fat crying.",
    "I don’t sweat, I sparkle.",
    "Deadlifts? More like dead-inside.",
    "Squat? I thought you said chicken nuggets.",
    "I can’t feel my face… or legs.",
    "Gym hair, don’t care.",

    "Strength grows by overcoming what felt impossible.",
    "Don’t stop when tired; stop when done.",
    "Do I even gym, bro? Sometimes.",
    "No pain, no gain.",
    "You don’t have to be extreme, just consistent.",
    "1% better every day adds up.",
    "Discipline beats motivation.",
    "Progress, not perfection.",
    "Your only limit is you.",
    "Train hard, stay humble.",
    "Stronger every single day.",
    "Burpees: created by Satan.",
    "Excuses don’t burn calories.",
    "Make sweat your best accessory.",
    "The pain you feel today is strength tomorrow.",
    "Pain is weakness leaving the body.",
    "Keep going, you’re closer than you think.",
    "Work hard in silence, let success roar.",
    "Fitness is a journey, not a race.",
    "You are your best project.",
    "Dream it. Believe it. Achieve it.",
    "Sore today, strong tomorrow.",
    "Fall in love with taking care of yourself.",
    "The body achieves what the mind believes.",
    "Good things take time."
];
